# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGaDHQnXTbeoC2q4RhgHwbpQigjUY4TX
"""

from bs4 import BeautifulSoup
from google.colab import files
import requests
import pandas as pd

url = 'https://id.wikipedia.org/wiki/Daftar_bandar_udara_di_Indonesia'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')
print(soup)

soup.find_all('table') [2]

table = soup.find_all('table') [2]

print(table)

soup.find('table', class_ = 'wikitable sortable')

world_titles = table.find_all('th')

world_titles

world_title_tables = [title.text.strip() for title in world_titles]

print(world_title_tables)

df = pd.DataFrame(columns = world_title_tables)
df

column_data = table.find_all('tr')

for row in column_data[1:]:
  row_data = row.find_all('td')
  individual_row_data = [data.text.strip() for data in row_data]

  while len(individual_row_data) < len(df.columns):
    individual_row_data.append(None)  # atau gunakan '' untuk string kosong
  if len(individual_row_data) == len(df.columns):
    length = len(df)
    df.loc[length] = individual_row_data
  else:
    print("Panjang data tidak sesuai dengan jumlah kolom DataFrame")

print(df)

csv_filename = 'daftar_bandar_udara_di_Indonesia.csv'
df.to_csv(csv_filename, index=False)
files.download(csv_filename)